### ISSUE TITLE
How long does it take to run ecospat.niche.equivalency.test?

### ISSUE THREAD

**Issue by raianu191** [ecospat/ecospat#14]
I have been trying to run this code for well over 24 hours now but have not received any results. I have used rep 1000 value for analysis. Is the process supposed to take this long a time?

**Comment by avephill** [comment]
It takes a long time with just 100 reps. For me, up to 20 minutes

**Comment by bpetitpi** [comment]
How many occurrences do you have ? And have you tried to play with the "ncores" parameter ?

If you want to extrapolate the time it takes, you can base your estimation about how long it takes to make the following analysis on your observed data :
1) apply ecospat.grid.clim.dyn() on your two taxa (e.g. z1 and z2)
2) apply the ecospat.niche.overlap()
3) multiply the time it takes for step 1 and 2 by the number of repetitions you set in the ecospat.niche.equivalency.test 

But again, if you work on a multicore computer, don't hesitate to use this ncores parameter.

**Comment by avephill** [comment]
Great, thank you for the feedback! I was mostly trying to contextualize raianu191's long run-time. I have a ton of occurrences (5,000+) so I'm not surprised that it takes a while.
The parallel computation with multiple cores works brilliantly.

I have noticed that using `ecospat.grid.clim.dyn_alt(..., kernel.method = "ks")` about halves the run-time, however, in ecospat v. 3.2 it seems that I can't change the kernel.method used in generating the simulated z1 and z2 in `ecospat.niche.equivalency.test()`. I've modified your function in order to use `kernel.method = "ks"` for both my observed and simulated z-values-- because my thinking is that the simulated values should use the same kernel.method as the observed when running the test? Let me know if this seems wrong.
