### ISSUE TITLE
All MAXENT models failing

### ISSUE THREAD

**Issue by kieranalthaus** [ecospat/ecospat#82]
I am trying to run an ESM using the MAXENT model option, but all ~100 bivariate models fail.
I redownloaded maxent.jar, and that did not fix the problem. Additionally, I tried running the MAXENT model on the "ecospat.testData," and it still failed all the models. 

I ran bivariate GLM models the same species I failed with, and those ran completely fine. Furthermore, I am completely up-to-date on all package versions. I cannot seem to find the reason for the mass failure of my models, when just 3-4 months ago they were working fine. Does anyone have any ideas as to what is wrong, or how I can fix it? 

Thank you!

**Comment by FlavienCollart** [comment]
Hello,
Do you have the Maxent software in your working directory and Java installed?

**Comment by kieranalthaus** [comment]
I do. It was all working a few months ago.

**Comment by FlavienCollart** [comment]
Hello,
Can you send us your script and the list of your packages and their versions + the path to your maxent software?

**Comment by FlavienCollart** [comment]
Hello again,
I've tested and ESM runs well with MAXENT using our testData. So, please send me all the stuffs asked in my previous comment, so that I can correctly pin point the issue

**Comment by FlavienCollart** [comment]
Hello,

Please try to download our new dev version (**devtools::install_github("ecospat/ecospat/ecospat@dev")** ). I did some changes on this kind of issues today.

**Comment by kieranalthaus** [comment]
I downloaded the dev version, but now my error is "Error in weighted.mean.default(x, weights2, na.rm = TRUE) : 
  'x' and 'w' must have the same length"

**Comment by FlavienCollart** [comment]
Hello,
Can you send me a script and your data to reproduce the error, so that I can correct it?

**Comment by kieranalthaus** [comment]
[Uploading DATA_ANALYSIS copy 2.zip…]()

**Comment by kieranalthaus** [comment]
Any word on the issue here?

**Comment by FlavienCollart** [comment]
Hello,
I have found the issues. It is you Data Split Table that is not correct. Some Runs do not have presences. It is working when I let the function generate the data.frame for the cross-validations. Please try to change your cross-validation table, making sure that occurrences are in the calibration and evaluation part. If you simply want to make a repeated split-sampling cross-validation, you can use the arguments "DataSplit" and "NbRunEval" instead of "DataSplitTable".

Please let me know if it is working.
